### PR TITLE
Create watchers with regexen

### PR DESCRIPTION
**Pull request by rgabo**
..to avoid compass deprecation warnings. Also, please try to get your fork pulled into the official gem, I'd love to be able to install 0.0.7 from rubygems.

Good job with fixing the relative path issue which was a mess and creating watchers automagically.

thanks,
Gabor

PS I also removed the puts watchers.inspect. Trust your code, works great! :)

### CODE REVIEW

**Comment by tarsolya** [comment]
+1

**Comment by balinterdi** [comment]
Yep, this would be an improvement.

**Comment by mraaroncruz** [comment]
Hi Gabor!  Fancy meeting you here ;)  
I would love to see this too.

**Comment by oliamb** [comment]
Sorry for the long delay. I'll try to find some time to push a 0.0.8 online soon.

**Pull request merged**
